### ISSUE TITLE
Exception: Attempted to call an undefined method named "getSourceContext" of class "Slame\WhiteLabelBundle\Twig\MultisiteLoader".

### ISSUE THREAD

**Issue by itinance** [simonoche/white-label-bundle#1]
After an composer-update we get the following exception:

> Attempted to call an undefined method named "getSourceContext" of class "Slame\WhiteLabelBundle\Twig\MultisiteLoader".

This is the composer.json:

```
    "require": {
        "php": ">=5.5.0",
        "symfony/symfony" : "2.7.*",

        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",

        "twig/extensions": "~1.1.0",

        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "~2.4",

        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",

        "incenteev/composer-parameter-handler": "~2.0",
        "fire015/flintstone": "^1.9",
        "fzaninotto/faker": "^1.5",
        "cocur/slugify" : "~1.1",
        "nesbot/carbon": "^1.20",
        "leaseweb/memcache-bundle": "*",
        "guzzlehttp/guzzle": "~6.0.2",
        "egulias/email-validator" : "~1.2",
        "jasny/twig-extensions": "*",

        "emanueleminotto/twig-cache-bundle": "1.0.2",

        "google/apiclient": "~1.1",
        "misd/phone-number-bundle": "~1.0",

        "itinance/Deployer": "dev-master",
        "itinance/tinygeo": "^0.2",
        "itinance/SimplifyTwigExtension": "dev-master",
        "itinance/php-html-parser": "dev-master",
        "itinance/doctrine-cache-adapter-with-site-context": "^0.2",

        "simonoche/white-label-bundle": "0.1.2",
        "willdurand/geocoder": "^3.1",

        "gedmo/doctrine-extensions": "dev-master",
        "jms/serializer-bundle": "^1.1",
        "mobiledetect/mobiledetectlib": "^2.8",
        "itinance/tiny-state-machine": "*"
    },

```

Any ideas?

**Comment by simonoche** [comment]
Hey there,

Honestly, I don't remember exactly what about this problem is ; but in my recent commits I fixed your issue by adding two functions in MultisiteLoader : getSourceContext() and getCode().

I suggest you to migrate to v2.0.1. But there is many changes (and improvements!), between 1.x and 2.x ; so if you choose this option, read the documentation carefully before upgrading !

Feel free to ask anything 👍 

I'll release a v0.1.4 now with theses changes as well

Cheers

**Comment by itinance** [comment]
Upgrading to 1.0.2 fixed this issue. 
Btw, v2.0.1 throwed exception "unknown 'hosts' in slame_white_label" (the part in config.yml). Have you changed the way of configuration in 2.0? (In readme it is still present like with v1)

**Comment by simonoche** [comment]
Oops you're right,
The main node is now "partners" instead of "hosts".
I updated the doc in branch v2-master
Thanks
Simon
